### ISSUE TITLE
Crash on startup do to wrong depencencies

### ISSUE THREAD

**Issue by bangetto** [cakeGit/Deepslate-Processing#1]
```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Create: Deepslate Processing' (create_deepslate_processing) ${version} with any version that is compatible with:
		 - minecraft 1.20.1
		 - fabricloader 0.15.11
		 - fabric-api 0.92.2+1.20.1
		 - create 0.5.1-f-build.1417+mc1.20.1
More details:
	 - Mod 'Create: Deepslate Processing' (create_deepslate_processing) ${version} requires version ${minecraft_version} of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'Create: Deepslate Processing' (create_deepslate_processing) ${version} requires version ${fabric_loader_version} of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.15.11!
	 - Mod 'Create: Deepslate Processing' (create_deepslate_processing) ${version} requires version ${fabric_api_version} of mod 'Fabric API' (fabric-api), but only the wrong version is present: 0.92.2+1.20.1!
	 - Mod 'Create: Deepslate Processing' (create_deepslate_processing) ${version} requires version ${create_version} of mod 'Create' (create), but only the wrong version is present: 0.5.1-f-build.1417+mc1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by cakeGit** [comment]
Seen this before it's an issue with the multi loader template, I'll get a fix to you in a second

**Comment by cakeGit** [comment]
Fixed in latest update
